# Generated by Django 5.2.17 on 2026-09-19 13:03

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginBucket",
            fields=[
                (
                    "key",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("count", models.PositiveIntegerField(default=0)),
                ("window", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("character", "character"),
                            ("clothing", "clothing"),
                            ("location", "location"),
                            ("motion", "motion"),
                        ],
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("key", models.CharField(max_length=255)),
                ("mime", models.CharField(max_length=64)),
                ("duration", models.PositiveIntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MfaDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("encrypted_secret", models.TextField()),
                ("last_counter", models.BigIntegerField(default=-1)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="New video", max_length=120)),
                ("config", models.JSONField(default=dict)),
                ("revision", models.PositiveIntegerField(default=1)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("part", models.CharField(max_length=16)),
                ("snapshot", models.JSONField()),
                ("request_key", models.UUIDField()),
                ("state", models.CharField(default="generating", max_length=20)),
                ("output_key", models.CharField(blank=True, max_length=255)),
                ("assembly_lease", models.DateTimeField(null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="studio.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Chunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("start", models.PositiveIntegerField()),
                ("duration", models.PositiveIntegerField()),
                ("prompt", models.TextField()),
                ("state", models.CharField(default="queued", max_length=20)),
                ("provider_id", models.CharField(blank=True, max_length=255)),
                ("output_key", models.CharField(blank=True, max_length=255)),
                ("error", models.CharField(blank=True, max_length=255)),
                ("cost", models.PositiveIntegerField()),
                ("attempt", models.PositiveIntegerField(default=1)),
                ("lease_until", models.DateTimeField(null=True)),
                ("next_poll", models.DateTimeField(null=True)),
                ("started", models.DateTimeField(null=True)),
                (
                    "motion_asset",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="studio.asset",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="studio.run",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("available", models.BigIntegerField(default=0)),
                ("held", models.BigIntegerField(default=0)),
                ("spent", models.BigIntegerField(default=0)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("available__gte", 0), ("held__gte", 0), ("spent__gte", 0)
                        ),
                        name="nonnegative_wallet",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Ledger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=150, unique=True)),
                ("kind", models.CharField(max_length=16)),
                ("amount", models.PositiveIntegerField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="studio.wallet",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="run",
            constraint=models.UniqueConstraint(
                fields=("project", "request_key"), name="unique_generation_request"
            ),
        ),
        migrations.AddConstraint(
            model_name="chunk",
            constraint=models.UniqueConstraint(
                fields=("run", "position"), name="unique_chunk_position"
            ),
        ),
    ]
