# Generated by Django 5.2.17 on 2026-09-20 11:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='provider_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='asset',
            name='provider_project',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='asset',
            name='provider_status',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_id', ''), _negated=True), fields=('owner', 'provider_project', 'provider_id'), name='unique_provider_asset_per_owner'),
        ),
    ]
