# Generated by Django 5.2.17 on 2026-09-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_asset_provider_id_asset_provider_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='analysis_status',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='asset',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
