# Generated by Django 5.2.17 on 2026-09-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_asset_analysis_status_asset_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='analysis_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
